version: '2'

services:
  adi:
    restart: always
    build: .
    expose:
      - '80'
    networks:
      - default
    environment:
      - VIRTUAL_HOST=www.adisolutions.com.co,adisolutions.com.co
      - LETSENCRYPT_HOST=www.adisolutions.com.co,adisolutions.com.co
      - LETSENCRYPT_EMAIL=andres.guerrero@adisolutions.com.co
networks:
  default:
    external:
      name: nginx-ssl_default
